[Fix] #101 - 덕큐피트 게임 로직 수정
playkuround/playkuround-iOS pull request #144
Opened 2024-08-18 08:40 UTC by Guryss

### 🐣Issue
closed #101 
<br/>

### 🐣Motivation
- 한 뷰에 여러 오리들이 나올 수 있도록 게임 로직 수정했습니다. 
<br/>

### 🐣Key Changes

<br/>

### 🐣Simulation

https://github.com/user-attachments/assets/b473c6b6-e08f-4f67-9314-ecb4faf343f9

<br/>

### 🐣To Reviewer

<br/>

### 🐣Reference

<br/>

2024-08-18 14:05 UTC, Guryss commented
게임 종료 및 중지 버튼 눌렀을 때 게임도 같이 멈추는 지 확인 필요

2024-08-18 16:50 UTC, leehe228 commented
오리가 나왔을 때 클릭 시 두 오리가 멀 경우 Bad가 뜨면 오리 두 마리가 사라져야 하는데 구현이 안되어 있는 것 같아요ㅠㅠ 지금은 버튼을 연타하면 bad가 뜨다가 결국 good이나 execellent가 뜨면서 넘어가집니다 ㅠㅠ 
지금 안드로이드 영상이 없어서 정확히 대조가 불가능한데 리듬게임? 처럼 사라졌던 것으로 기억합니다!! 한 번 확인 부탁드려요

<video width="380px" src="https://github.com/user-attachments/assets/a16931f5-e84f-4d8a-85e0-db26d4df4e70">

2024-08-18 16:50 UTC, leehe228 requested changes
잘 작동함은 확인했는데 코멘트 하나 확인 부탁드려요!!!

2024-08-20 15:31 UTC, Guryss commented
@leehe228 
말씀하신 이슈 해결했습니다!


https://github.com/user-attachments/assets/7dc1e9be-f675-47e5-bf33-d1d0c1627146

2024-08-20 16:15 UTC, leehe228 approved these changes
잘 작동하는거 확인했습니다.
말씀하셨던 가끔 타이머 (3, 2, 1)에서 중지되는 에러는 제 코드쪽 문제 같아서 확인해보겠습니다.
고생 많으셨습니다!! 👍🏻

2024-08-20 16:23 UTC, leehe228 commented
엇 근데 방금확인해보니까 일시정지했을때 게임이 안멈추는 것 같아요!

2024-08-20 17:05 UTC, merged