[Feat] #154 - 앱 내 SoundManager를 통해 사운드 적용
playkuround/playkuround-iOS pull request #171
Opened 2024-08-23 08:01 UTC by Guryss

### 🐣Issue
- closed #154 
<br/>

### 🐣Motivation
- 앱 내 사운드 적용 완료했습니다. 
<br/>

### 🐣Key Changes
- 기본적으로 깔리는 배경음악은 싱글톤 패턴을 적용하지 않고 인스턴스를 활용하여 RootView에 onAppear 되었을 때 적용되도록 구현했습니다. 
https://github.com/playkuround/playkuround-iOS/blob/f2f86f9a8c06c5791fa826ebf8a1743c9b46a732/playkuround-iOS/playkuround_iOSApp.swift#L12-L22

- 이외에 다른 음악들은 싱글톤 패턴으로 관리하여 적용할 수 있도록 했습니다. 

<br/>

### 🐣Simulation

<br/>

### 🐣To Reviewer

<br/>

### 🐣Reference

<br/>

2024-08-23 08:23 UTC, leehe228 commented
@Guryss 홈 화면으로 나가서 앱이 백그라운드에서 돌 때도 배경 음악이 계속 나오네요 수정이 필요해보입니다

2024-08-23 12:33 UTC, Guryss commented
> @Guryss 홈 화면으로 나가서 앱이 백그라운드에서 돌 때도 배경 음악이 계속 나오네요 수정이 필요해보입니다

저도 이부분 확인했는데 음악이 계속 나오나요? 전 음악이 멈추긴 했습니다

2024-08-23 14:00 UTC, leehe228 commented
@Guryss 실제 기기로 했을 때 멈추긴 멈추는데 홈으로 나가고 약 1~2초 정도 딜레이가 있은 후 멈추네요 좀 어색하긴 한데 크리티컬하지 않으니, 추후 수정해도 괜찮을 것 같습니다! 추가적으로 테스트하다가 발견한 건데 게임 진행 중에 홈으로 나갔을 때 일반적으로라면 일시정지가 자동으로 되어야 하는데 게임이 백그라운드에서 계속 돌더라구요 이거도 추후 수정하겠습니다.

2024-08-23 14:05 UTC, leehe228 commented on playkuround-iOS/Views/Games/SurviveGame/SurviveGameViewModel.swift
> +        }
이 부분이 로직이 수정되어서 게임 플레이해보면 하트가 1개일 때 닿으면 죽어야 하는데 하트 0개가 되었다가 한번 더 닿으면 죽습니다. 로직이 변경되면 안될 것 같아요

아래처럼 로직은 유지해야 할 것 같습니다
```swift
func duckkuHit() {
    self.life -= 1
    
    if self.life == 0 {
        soundManager.playSound(sound: .microbeEnd)
        finishGame()
    } else {
        soundManager.playSound(sound: .microbeHit)
    }
}
```

2024-08-23 14:06 UTC, leehe228 requested changes
수고하셨습니다. 리뷰 하나 확인해주세요!

2024-08-23 17:22 UTC, Guryss commented on playkuround-iOS/Views/Games/SurviveGame/SurviveGameViewModel.swift
> +        }
넵 수정했습니당! 감사합니다

2024-08-23 17:56 UTC, Guryss commented
> @Guryss 실제 기기로 했을 때 멈추긴 멈추는데 홈으로 나가고 약 1~2초 정도 딜레이가 있은 후 멈추네요 좀 어색하긴 한데 크리티컬하지 않으니, 추후 수정해도 괜찮을 것 같습니다! 추가적으로 테스트하다가 발견한 건데 게임 진행 중에 홈으로 나갔을 때 일반적으로라면 일시정지가 자동으로 되어야 하는데 게임이 백그라운드에서 계속 돌더라구요 이거도 추후 수정하겠습니다.

해당 이슈 수정하여 반영해두었습니다 ! 최근 커밋 확인해주세요. 꼼꼼한 확인 감사합니당.


https://github.com/user-attachments/assets/18d00904-e65a-400e-bf62-499feb809a03

2024-08-24 01:15 UTC, leehe228 approved these changes
잘 작동하는거 확인했습니다! 수고많으셨어요!!!👍🏻

2024-08-24 01:49 UTC, merged