[Feat] #20 - RootView 구현 및 로그인 및 회원가입 flow 구현
playkuround/playkuround-iOS pull request #45
Opened 2024-03-28 13:24 UTC by leehe228

### 🐣Issue
closed #20 
<br/>

### 🐣Motivation
RootView와 RootViewModel을 구현하고 로그인 - 회원가입 로직을 구현했습니다.
이에 관련된 부가적인 작업들도 진행했습니다.
(이 branch approve and merge 이후, 위치 권한 요청 뷰 추가 예정!)
<br/>

### 🐣Key Changes
- RootView 추가
- RootViewModel 추가
- 로그인, 회원가입 로직 구현
<br/>

**`RootView`**
```swift
ZStack {
    switch viewModel.currentView {
    case .main:
        MainView(viewModel: viewModel, mapViewModel: mapViewModel)
    case .login:
        LoginView(viewModel: viewModel)
```
- `RootView`는 위와 같이 ViewModel의 currentView @Published 변수로 뷰를 컨트롤합니다
<br/>

**`RootViewModel`**
```swift
final class RootViewModel: ObservableObject {
    // current presenting view type
    @Published var currentView: ViewType = .main
    
    // loading
    @Published var isLoading: Bool = true
    
    // Network Manager Instance
    @Published var networkManager = NetworkManager()
    // ...
```
- `RootViewModel`는 위와 같은 멤버 변수를 가지고 있습니다.
- `currentView`: 현재 `RootView`에서 보여주는 뷰를 컨트롤
- `isLoading`: 로딩 뷰 표시 여부 
<br/>

```swift
// View Transition
viewModel.transition(to: .home)
```
- 다른 뷰에서는 위와 같이 `transition` method를 호출해서 `RootView`에게 뷰 변경을 요청할 수 있음
<br/>

```swift
viewModel.logout()
```
- 서버에서 토큰 정보를 지우는 logout API를 호출하고, 앱 로컬 DB에서 토큰을 제거, `MainView`로 이동
<br/>

```swift
enum ViewType {
    // main
    case main
    
    // login
    case login
    // ...
```
- `enum ViewType`의 정의, RootView에서 컨트롤하는 뷰의 경우 `case`를 추가해서 사용하면 됩니다
<br/>

**기타 변경 사항**
- 로그인 및 회원가입 로직 구현 (이메일 인증 관련 API, 회원가입 API 연결)
<br/>

### 🐣Simulation
https://github.com/playkuround/playkuround-iOS/assets/37548919/7248d130-406a-4ebd-8cb3-f7763fa44c84
- 메인 - 로그인(이메일 인증) - 회원가입 - 홈
- 이미 가입된 경우: (로그아웃) - 로그인(이메일 인증) - 홈 (토큰 발급 후 자동 로그인)
- 앱 실행 시: 메인 - 홈 (토큰 검사 후 자동 로그인)
<br/>

### 🐣To Reviewer
변경사항이 아주 많아서 놓치거나 비효율적으로 짠 코드나 불필요한 코드가 많을수도 있을 것 같습니다 (아무리 봐도 안보여요)
아주 사소하더라도 고칠 점이 보이면 부담 갖지 말고 지적해주시면 감사드리겠습니다!
<br/>

### 🐣Reference
- [@Published 백그라운드 실행 시 오류, 메인 스레드에서 실행 방법](https://seons-dev.tistory.com/entry/Swift-DispatchQueue란-GCD-Grand-Central-Dispatch)
<br/>

2024-03-28 16:10 UTC, Guryss requested changes
수고했숴요 👏  질문이 조꼼 있어서 리뷰 확인해주심 좋을 것 같습니당 👍

2024-03-28 16:10 UTC, Guryss commented on playkuround-iOS/Views/Root/RequestPermissionView.swift
> +                            .padding(.bottom, 30)
P1;
`kerning(-0.41)` 적용해주세요!

2024-03-28 16:10 UTC, Guryss commented on playkuround-iOS/Views/Root/RequestPermissionView.swift
> +                                    .font(.neo18)
P1;
여기도 kerning 적용해주기!

2024-03-28 16:10 UTC, Guryss commented on playkuround-iOS/Views/Login/LoginBottomSheetView.swift
> -        .animation(.easeInOut, value: isPresented)
P1;
헉 이거 바텀시트인데 애니메이션 삭제해도 문제가 없나용?

2024-03-28 16:10 UTC, Guryss commented on playkuround-iOS/Views/Login/LoginView.swift
> +
P2;
이 코드가 무엇인지 궁금합니당

2024-03-28 16:10 UTC, Guryss commented on playkuround-iOS/Views/Main/MainView.swift
> +        // reissue API 호출
와 로직 .. 수고 많았네요 👍

2024-03-28 16:10 UTC, Guryss commented on playkuround-iOS/Views/Register/RegisterMajorView.swift
> +                        .frame(maxWidth: .infinity)
P2;
여기랑 아래 이미지에서 `maxWidth`로 변경한 이유는 무엇일까용?

2024-03-28 16:10 UTC, Guryss commented on playkuround-iOS/Views/Root/RootView.swift
> +    }
👍👍 잘쓸게요 굿

근데 해당 함수가 RootViewModel에도 있던뎅 ... 두 파일에 둘 다 필요한 함수일까요??

2024-03-28 17:39 UTC, leehe228 commented on playkuround-iOS/Views/Root/RequestPermissionView.swift
> +                            .padding(.bottom, 30)
헉 생각지도 못했네요.. 죄송합니다 지적해주셔서 감사합니다

2024-03-28 17:49 UTC, leehe228 commented on playkuround-iOS/Views/Login/LoginView.swift
> +
위 코드는 앱 내 DB에 `target` 즉, 사용자가 로그인 화면에서 입력한 이메일을 저장한 코드입니다!
왜나면 다른 뷰 (`RegisterNicknameView`)에서 사용자가 로그인 화면에서 입력했던 이메일을 회원가입 API에 입력해줘야 하기 때문입니다!
객체나 구조체를 만들어서 저장할 수 있지만, 작은 정보들은 저렇게 저장을 해서 사용하더라구요.
주로, 자동 로그인(토큰, 세션 값), 앱 설치 후 첫 접속 여부 등을 판별할 때 주로 사용한다고 합니다!

위 코드에서 저장된 이메일 값은 `RegisterNicknameView` 151째줄~ 에서 사용됩니다!
<img width="600" alt="image" src="https://github.com/playkuround/playkuround-iOS/assets/37548919/859efa51-6d51-4b25-a82d-5338a9532466">

2024-03-28 18:06 UTC, leehe228 commented on playkuround-iOS/Views/Register/RegisterMajorView.swift
> +                        .frame(maxWidth: .infinity)
이미지나 다른 오브젝트에 `.frame(width: .infinity)`를 사용하면 아래와 같은 오류?가 발생하더라구요!
<img width="438" alt="image" src="https://github.com/playkuround/playkuround-iOS/assets/37548919/4ac61ebb-680d-4b50-92fa-2fbdf12ab525">
<img width="548" alt="image" src="https://github.com/playkuround/playkuround-iOS/assets/37548919/d5a8aa36-adc1-4391-8253-c1702280e093">
찾아보니, `width`에는 `.infinity`를 사용할 수 없고, 이미지나 오브젝트에 frame을 적용해서 너비나 높이에 적용할때는 `maxWidth`에 `infinity`를 써야 한다고 합니다!

2024-03-28 18:07 UTC, leehe228 commented on playkuround-iOS/Views/Root/RootView.swift
> +    }
헉.. 그렇네요.. 아무리 봐도 안보이더니 감사합니다..ㅎ 더 꼼꼼히 확인할게요..ㅠ

2024-03-28 18:13 UTC, leehe228 commented on playkuround-iOS/Views/Login/LoginBottomSheetView.swift
> -        .animation(.easeInOut, value: isPresented)
혹시 몰라 방금 확인해보았는데, 저 `.animation(.easeInOut, value: isPresented)` 코드가 있어도 애니메이션 적용이 안되네요!
대신에 아래 코드에 animation을 적용했습니다!
```swift
withAnimation(.spring) {
    isTimerFinished = true
}
```

2024-03-28 18:16 UTC, leehe228 commented on playkuround-iOS/Views/Login/LoginBottomSheetView.swift
> -        .animation(.easeInOut, value: isPresented)
그리고 `.easeInOut`이랑 `.spring`을 비교해봤는데 `.spring`이 조금 더 자연스러운 것 같아서 변경했습니다!

2024-03-28 18:24 UTC, leehe228 commented on playkuround-iOS/Views/Login/LoginView.swift
> +
혹시 알고계신 더 좋은 방법 있으시면 알려주시면 감사하겠습니다..ㅎ!!!

2024-03-28 18:27 UTC, leehe228 commented
리뷰로 달아주신 모든 사항 반영했습니다!! 여러 번 봐도 안보이던게 큰 실수들이 많았네요 정말 감사드립니다!! 
감사합니다!!👍🏻👍🏻
- BottomSheet에 애니메이션 적용
- 텍스트 kerning 적용
- currentAppVersion 함수 중복 제거

2024-03-29 02:34 UTC, Guryss commented on playkuround-iOS/Views/Login/LoginBottomSheetView.swift
> -        .animation(.easeInOut, value: isPresented)
흠 그렇군요 알겠습니다!

2024-03-29 02:36 UTC, Guryss commented on playkuround-iOS/Views/Login/LoginView.swift
> +
그렇군요!! 저도 확실히 잘 아는것이 아니었어서 궁금해서 물어본거였습니당

2024-03-29 02:36 UTC, Guryss approved these changes
LGTM

2024-03-29 03:47 UTC, merged