[Design] #46 - 일시정지뷰, 카운트다운 뷰, 10초를 맞춰봐 게임 UI 구현
playkuround/playkuround-iOS pull request #50
Opened 2024-03-29 15:25 UTC by leehe228

### 🐣Issue
closed #46 
<br/>

### 🐣Motivation
일시정지뷰 (`GamePauseView`), 카운트다운뷰 (`CountdownView`), 10초를 맞춰봐 게임 뷰 (`TimerGameView`) UI를 구현했습니다
<br/>

### 🐣Key Changes
아래 3개 뷰의 디자인을 구현했습니다
- `GamePauseView`
- `TimerGameView`
- `CountdownView`

일시정지 뷰에 필요한 이미지를 추가했습니다
- BluePauseButton을 포함한 총 6개 이미지
<br/>

### 🐣Simulation
AppStore 보시면 알 수 있듯 iPhone 스크린 타입은 총 3종류입니다! (Dynamic Island, Notch, Home Button)
3개 타입은 화면 크기(면적)만 다르고 비율은 같으므로, 특히 게임쪽은 3종에 대해 각각 테스트해보는게 좋을 듯 합니다!
각 타입에 대한 대표 기종은 아래와 같아요!

**Dynamic Island (iPhone 15 Pro)**
<img width="280px" alt="" src="https://github.com/playkuround/playkuround-iOS/assets/37548919/d47268d9-546d-43a0-be7f-c6dfae7e4aa7"/>
<br/>

**Notch(iPhone 14)**
<img width="280px" alt="" src="https://github.com/playkuround/playkuround-iOS/assets/37548919/0a55c8b6-08f8-46f8-8ca8-694f456baed2"/>
<br/>

**Home Button(iPhone SE3)**
<img width="280px" alt="" src="https://github.com/playkuround/playkuround-iOS/assets/37548919/07c69fbb-e524-450d-bfeb-c5adf3a8ab63"/>
<br/>

**`GamePauseView`**
<img width="280px" alt="" src="https://github.com/playkuround/playkuround-iOS/assets/37548919/f1e39bf1-dfb5-4da9-931a-0e5370723ec5">
<br/>

**`CountdownView`**
<img width="200px" alt="image" src="https://github.com/playkuround/playkuround-iOS/assets/37548919/469bdb23-405c-4cad-b1cc-b86628f0526c">
<img width="200px" alt="image" src="https://github.com/playkuround/playkuround-iOS/assets/37548919/fdfd3002-b200-43f0-ba59-7be9af151f35">
<img width="200px" alt="image" src="https://github.com/playkuround/playkuround-iOS/assets/37548919/19bdad48-f21a-4cc8-954b-8ae14e3433db">
- `@Binding var countdown` 변수값에 따라 카운트다운 뷰 표시

### 🐣To Reviewer
디자인 구현 완료 이후, GameViewModel 구현하여 게임을 구현할게요!
<br/>

### 🐣Reference
X
<br/>

2024-03-29 17:00 UTC, Guryss requested changes
수고많았습니다!
약간 빠진 부분이 있는 것 같아 리뷰 확인해서 다시 수정해주심 될 것 같아요.

참고로 `GamePauseView`안에 `@Binding`을 넣어주는 건 어떨지 의견 내봅니다~

2024-03-29 17:00 UTC, Guryss commented on playkuround-iOS/Assets.xcassets/ColorAssets/kuLightYellow.colorset/Contents.json
> +      },
P1;
해당 컬러는 백그라운드 색상으로 쓰이는 것 같으니 naming을 `kuLightYellowBackground`로 설정해주면 더 명확할 것 같습니다!

2024-03-29 17:00 UTC, Guryss commented on playkuround-iOS/Assets.xcassets/ImageAssets/Game/Time/timeSuccessIcon.imageset/timeSuccessIcon.svg
P1;
게임 성공했을 때 해당 뷰는 이미지가 아니라 gif처럼 애니메이션이 있어야 해요!!
드라이브 참고해보면 이미지가 2개가 있답니다 ..
애니메이션뷰로 수정해서 다시 올려주세용

2024-03-29 17:00 UTC, Guryss commented on playkuround-iOS/Views/Games/GamePauseView.swift
> +                            .foregroundStyle(.black)
P1;
`.black` 이 아니라서 `.kuText`로 수정해주세요~

2024-03-29 17:00 UTC, Guryss commented on playkuround-iOS/Views/Games/GamePauseView.swift
> +                            .foregroundStyle(.black)
여기도~

2024-03-29 17:00 UTC, Guryss commented on playkuround-iOS/Views/Games/TimerGame/TimerGameView.swift
> +                // } else {
P1;
필요 없는 주석은 삭제해주세요

2024-03-29 17:00 UTC, Guryss commented on playkuround-iOS/Views/Games/TimerGame/TimerGameView.swift
> +                    .foregroundStyle(.kuText)
P1;
VStack안에 "10초안에 가까워졌을 때~" 멘트가 빠졌네요. 넣어주세요!

2024-03-29 17:06 UTC, leehe228 commented on playkuround-iOS/Views/Games/GamePauseView.swift
> +                            .foregroundStyle(.black)
로그아웃 페이지 글자랑 색이 다르군요.. 감사합니다

2024-03-29 17:13 UTC, leehe228 commented on playkuround-iOS/Assets.xcassets/ImageAssets/Game/Time/timeSuccessIcon.imageset/timeSuccessIcon.svg
감사합니다! 게임쪽 봤었는데 이미지가 없길래 애니메이션이 아니구나 싶었는데 다른 곳에 있었군요..

2024-03-29 17:21 UTC, leehe228 commented
`@Binding`은 넣어둘까 싶었는데 GameViewModel을 구현하면 Binding이 아니라 `gameViewModel.isPauseViewPresented` 이거나 `gameViewModel.gameContinue()` 이렇게 사용하게 될 것 같아서 제외했습니다!

2024-03-29 17:55 UTC, leehe228 commented
핑계아닌 핑계를 대자면 중간에 텍스트를 빼버렸던 이유가 이거처럼 기종에 대해서 조절이 아주 어렵더라구요
계속 해보다가 최선의 방법이 안떠올라서 제쳤다가 깜빡한 것 같아요
이걸 당시에는 ViewModel에서 기종별로 스크린의 height별로 구분해서 분기처리를 해줘야 하나, 아니면 비율로 가야하나, 고민을 했었습니다.
참고로 사진이 좌, 우가 잘려있어서 현재 좌/우의 너비를 스크린에 맞춘거라 이동이 애매합니다.
위치가 바뀌면 내부 텍스트랑 버튼도 바뀌고요..
현재는 제가 최대한 안겹치도록 패딩으로 조정을 해놓은건데 피그마랑 비율이 달라졌습니다.
일단 보기에 괜찮다면 그냥 이렇게 가도 될 것 같고, 최대한 맞춰야 한다면.. 일단 UI구현이니 위처럼 구현해두고 Game 기능 개발할 때 한 번 위치나 비율을 다시 조정해보겠습니다.

**15 Pro**
<img width="220px" alt="image" src="https://github.com/playkuround/playkuround-iOS/assets/37548919/fed14bbf-3e7f-4e68-8a66-b4b35936dbbf">

**SE3**
<img width="220px" alt="image" src="https://github.com/playkuround/playkuround-iOS/assets/37548919/0985f5ed-d875-4bbb-9e0c-5568064c7e44">

**14**
<img width="220px" alt="image" src="https://github.com/playkuround/playkuround-iOS/assets/37548919/288b43d1-004b-409f-85fc-24a491b3748d">

2024-03-29 17:58 UTC, leehe228 commented
리뷰 사항 전부 반영 완료했습니다!
일단은 UI위주로만 구현해두고 GameViewModel 만든 후 실제 ViewModel 붙이면서 작업을 더 해야할 것 같습니다.

2024-03-29 18:36 UTC, Guryss commented
> 핑계아닌 핑계를 대자면 중간에 텍스트를 빼버렸던 이유가 이거처럼 기종에 대해서 조절이 아주 어렵더라구요 계속 해보다가 최선의 방법이 안떠올라서 제쳤다가 깜빡한 것 같아요 이걸 당시에는 ViewModel에서 기종별로 스크린의 height별로 구분해서 분기처리를 해줘야 하나, 아니면 비율로 가야하나, 고민을 했었습니다. 참고로 사진이 좌, 우가 잘려있어서 현재 좌/우의 너비를 스크린에 맞춘거라 이동이 애매합니다. 위치가 바뀌면 내부 텍스트랑 버튼도 바뀌고요.. 현재는 제가 최대한 안겹치도록 패딩으로 조정을 해놓은건데 피그마랑 비율이 달라졌습니다. 일단 보기에 괜찮다면 그냥 이렇게 가도 될 것 같고, 최대한 맞춰야 한다면.. 일단 UI구현이니 위처럼 구현해두고 Game 기능 개발할 때 한 번 위치나 비율을 다시 조정해보겠습니다.
> 
> **15 Pro** <img alt="image" width="220px" src="https://private-user-images.githubusercontent.com/37548919/318108934-fed14bbf-3e7f-4e68-8a66-b4b35936dbbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3Mzc0NzUsIm5iZiI6MTcxMTczNzE3NSwicGF0aCI6Ii8zNzU0ODkxOS8zMTgxMDg5MzQtZmVkMTRiYmYtM2U3Zi00ZTY4LThhNjYtYjRiMzU5MzZkYmJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDE4MzI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1NjRlNTYzMWUxZjUwNjQ2MTdkYWQ3YzMwNmQ5MGNlODU0MmJiMGNjNzMxZjk0MDI1YmQwNTQ3Y2NkMTJlZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bt8YPbFldWQ_uNnkTn4XPJaAQfvFyZ0ry8stqOc-Ybk">
> 
> **SE3** <img alt="image" width="220px" src="https://private-user-images.githubusercontent.com/37548919/318108975-0985f5ed-d875-4bbb-9e0c-5568064c7e44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3Mzc0NzUsIm5iZiI6MTcxMTczNzE3NSwicGF0aCI6Ii8zNzU0ODkxOS8zMTgxMDg5NzUtMDk4NWY1ZWQtZDg3NS00YmJiLTllMGMtNTU2ODA2NGM3ZTQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDE4MzI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0YzZhYzJkNzMzNmY0ZGUxNjk5YTQ0ZDk1NmZmYTEzNzFjN2EyM2M0YTcyYmU4YmRhN2M3YmYzOGRhYTNjYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g3dygWHfslpp5ctL4DFAEykJ_tgD9vLLTq28sCY5MBo">
> 
> **14** <img alt="image" width="220px" src="https://private-user-images.githubusercontent.com/37548919/318109140-288b43d1-004b-409f-85fc-24a491b3748d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3Mzc0NzUsIm5iZiI6MTcxMTczNzE3NSwicGF0aCI6Ii8zNzU0ODkxOS8zMTgxMDkxNDAtMjg4YjQzZDEtMDA0Yi00MDlmLTg1ZmMtMjRhNDkxYjM3NDhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDE4MzI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwM2FlYTNiNjIyM2Y5ZGRiZWZjMmMxOTEwZDhkZGUxMzgzMGUwNmZmMjk0MTU2YTc1YmU0ZmI1NjYzYzM3Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qlccL4p9iVoarCx6vCOgEszIuRnyvaaMbI5_Mspjurw">

흠 그렇군요 .. 그렇다면 해당 텍스트를 `ZStack`에 넣어두고 뒤에 오는 `VStack`에 패딩을 걸어두는 건 어떨까요? 
그렇게 한다면 뷰 마다의 여백이 생기진 않을 것 같아요!

2024-03-29 18:43 UTC, Guryss reviewed
화면의 사이즈에 따라 뷰의 크기를 지정할 수 있는 `GeometryReader`를 이용해서 해당 문제를 해결 할 수도 있을 것 같습니다. 
어짜피 4월동안 할 부분이니까 `GeometryReader` 한번 적용해서 문제 해결해보는 건 어떨까요!?

2024-03-29 18:43 UTC, Guryss commented on playkuround-iOS/Views/Games/TimerGame/TimerGameView.swift
> +                    .multilineTextAlignment(.center)
해당 텍스트를 ZStack에 한번 넣어서 패딩 주면 뷰마다 화면이 깨지지 않을 수도 있지 않을까요?

2024-03-29 18:43 UTC, Guryss commented on playkuround-iOS/Views/Games/TimerGame/TimerGameView.swift
> +//                    .padding(.top, 20)
주석 지워주세용

2024-03-29 18:43 UTC, Guryss commented on playkuround-iOS/Views/Games/TimerGame/TimerGameView.swift
> +//                    .padding(.top, 20)
아 임시로 해놓은거군요 ㅇㅋㅇㅋ

2024-03-29 18:43 UTC, Guryss commented
제가 제안한 부분 한번 시도 해보고 .. 연락주세염!

2024-03-29 19:31 UTC, leehe228 commented on playkuround-iOS/Views/Games/TimerGame/TimerGameView.swift
> +//                    .padding(.top, 20)
아 넵... if문으로 분기처리할 부분이라 남겨두었습닌다..!

2024-03-29 19:33 UTC, leehe228 commented on playkuround-iOS/Views/Games/TimerGame/TimerGameView.swift
> +                    .multilineTextAlignment(.center)
넵 위 방법도 적용해보겠습니다

2024-03-29 19:34 UTC, leehe228 commented
좋은 의견 감사합니다. 좀 더 찾아보니 SafeAreaPadding이라고, 기종에 상관 없이 패딩을 줄 수 있는 방법도 있고 GeometryReader를 사용하는 방법도 있고 다양할 것 같습니다. (잘 될지는 모르겠네요)
시간이 있으니 이것저것 시도해보고 말씀드리겠습니다!

2024-03-30 13:51 UTC, leehe228 commented
**`TimerGameView` 수정**
<img width="280px" alt="image" src="https://github.com/playkuround/playkuround-iOS/assets/37548919/cc4a63df-6743-4ead-8e7d-e5d3312f7366"> <br/>
<img width="280px" alt="image" src="https://github.com/playkuround/playkuround-iOS/assets/37548919/4a6d37eb-070e-445c-a6d0-830e2e861abf"> <br/>
- 빨간색 선은 텍스트의 위치와 크기를 쉽게 알아볼 수 있도록 임시로 넣어두었습니다.
- 상단의 네비게이션바의 높이가 생각보다 크고 기종에 따라 크기를 변하게 할 수 없어서 아래와 같은 조건으로 반응형으로 만들었습니다.
    - 네비게이션바 > 텍스트 > 사진 순으로 배치
    - 네비게이션바의 높이는 변경할 수 X
    - 텍스트는 잘리지 않으려면 최소 높이 60px는 필요
    - 시계 사진의 아래는 일부 잘려도 됨

위 조건을 만족시키기 위해 배치를 
- 상단 정렬, 네비게이션 바
- 네비게이션바 아래에 텍스트를 적절한 높이로 배치
- 3종류의 화면 타입에 대해 보니 작은 화면(홈버튼)은 화면 높이가 700 미만이고, 노치나 dynamic island는 700 이상임
- 두 분기로 나누어, 홈화면인 경우 텍스트의 높이를 60으로, 나머지 경우는 90으로 하여 비율을 맞추도록 하였음
- 사진의 경우 텍스트에 대해 overlay로 적용 및 offset(y: 100)을 주어 하단 일부가 잘리더라도 텍스트와의 일정 간격을 반드시 유지하도록 함

아래는 간단한 구조임
```swift
VStack {
    Spacer()
    Text("설명")
    Spacer()
}
.frame(height: geometry.size.height > 700 ? 90 : 60)
.customNavigationBar { }
.overlay {
    Image("시계 배경")
        .offset(y: 100)
        .overlay {
            VStack {
                // 00:00, 성공 실패 여부, 버튼
            }
            .offset(y: 110)
        }
}
```

2024-03-30 14:11 UTC, Guryss reviewed
굿굿 수고했어요!!

리뷰 한번 확인해주세요 :)

2024-03-30 14:11 UTC, Guryss commented on playkuround-iOS/Views/Games/CountdownView.swift
> +
P2;
enum값으로 관리하는 건 어떨까요??

2024-03-30 14:11 UTC, Guryss commented on playkuround-iOS/Views/Games/TimerGame/TimerGameView.swift
> +                VStack() {
P1;
VStack에 속성 따로 넣을 필요 없다면 괄호 없애도 될 것 같아요!

2024-03-30 14:11 UTC, Guryss commented on playkuround-iOS/Views/Games/TimerGame/TimerGameView.swift
> +                .frame(height: geometry.size.height > 700 ? 90 : 60)
분기처리 해주었군요 .. 굿

2024-03-30 14:15 UTC, leehe228 commented on playkuround-iOS/Views/Games/TimerGame/TimerGameView.swift
> +                .frame(height: geometry.size.height > 700 ? 90 : 60)
뭔가 굉장히 불편한데 또 이거만큼 잘 작동하는걸 못찾아서.. 나중에 더 깔끔한 방법 생각나거나 찾게되면 수정하겠습니다!!

2024-03-30 14:18 UTC, leehe228 commented on playkuround-iOS/Views/Games/CountdownView.swift
> +
타이머 붙여서 3, 2, 1 이렇게 인덱스로 접근하려 enum이 안정성이 더 좋을 것 같네요 수정하겠습니다!

2024-03-30 14:28 UTC, leehe228 commented
리뷰 반영하여 수정했습니다
- 컨벤션: `VStack` 괄호 제거
- 카운트다운 이미지 `enum`으로 변경 및 뷰에 적용

2024-03-30 14:33 UTC, Guryss commented on playkuround-iOS/Views/Games/CountdownView.swift
> +    @State var countdown: Int
이거 Binding이었는데 State로 바뀌었어요!

2024-03-30 14:34 UTC, Guryss approved these changes
수고했습니다~ 충돌만 해결해주시고 머지해주세요!

2024-03-30 15:01 UTC, merged