[Feat] #70 - 건쏠지식 게임 로직 구현
playkuround/playkuround-iOS pull request #71
Opened 2024-04-23 05:27 UTC by Guryss

### 🐣Issue
closed #70 
<br/>

### 🐣Motivation
- 건쏠지식 게임 로직 구현했습니다. 
<br/>

### 🐣Key Changes
https://github.com/playkuround/playkuround-iOS/blob/0cb9826b879b6fedfa110ad0dc382412be745c68/playkuround-iOS/Views/Games/QuizGame/QuizBlockView.swift#L38-L62
해당 부분은 블록을 클릭했을 때 뷰에서 처리해야 할 부분을 구현한 것입니다.
- `onTapGesture`를 통해 정답인지 아닌지를 구분합니다.
- `disabled`를 통해 결과 이후 `normal`이 아닌 블록의 터치 이벤트를 막습니다.
- `onChange`를 통해 선택한 블록 이외에는 `unable` 처리를 합니다.
- `onReceive`를 통해 타이머 시간이 경과되면 모든 블록을 다시 normal로 변경합니다.

ViewModel에 코드를 빼내는 부분이 살짝 어려워서 ... 뷰 짜는 코드에 게임 로직 코드도 들어있는 것 같아요 ㅠㅠ
- 수정해야 할 부분 있으면 말해주세요~!
<br/>

### 🐣Simulation
https://github.com/playkuround/playkuround-iOS/assets/102604192/04511cfd-3cab-4d17-9f85-5e26593b87f6

https://github.com/playkuround/playkuround-iOS/assets/102604192/43faab12-6ee3-4737-bd3f-f741296962c6

<br/>

### 🐣To Reviewer
- 정답일 때엔 나머지 버튼들이 unable이 되지 않습니다 .. .최대한 해결해보려 노력했으나 이부분이 해결되지 않네요 ㅠㅠ
근데 정답일 때엔 백그라운드 어둡게 처리해서 어차피 터치 이벤트는 반영되지 않아 ... 일단 두었습니다. ㅎㅎ
<br/>

### 🐣Reference

<br/>

2024-04-25 16:04 UTC, leehe228 commented
P1;
<video src="https://github.com/playkuround/playkuround-iOS/assets/37548919/4e222661-35d2-415e-a520-b69c29df99a7" width="280px"/>

게임 접속 시 다른 문제가 보였다가 문제로 넘어가는게 보입니다
아마 default index가 초기에 nil으로 설정되어 있어서 언래핑 과정에서 ?? 0 → 0번 문제가 보였다가 인덱스가 지정되면서 위 처럼 보이는 것 같아 보입니다 (json parsing이 별도의 스레드라 늦더라구요..)

제 생각에 해결책은 
1. QuizData.json 파일에 문제와 정답지 모두 `""`(empty string)으로 설정한 dummy 데이터를 채운 0번 인덱스를 추가
2. default index를 -1로 설정하고, 문제와 정답지가 보이는 뷰를 if문을 걸어둠 (`if vm.randomNumber >= 0 { // 뷰 }`) 즉 index가 0 이상일 때만 뷰가 보이도록!

위 두 방법처럼 처리 해두면 문제가 해결되지 않을까 싶습니다. (지난 앱 개발때도 json 읽어서 데이터화 하는게 별도의 스레드로 처리되어 저런 현상이 발생하더라구요. 그래서 위처럼 해결을 했습니다. (저는 2번으로 했어요)

2024-04-25 16:07 UTC, leehe228 commented
기획서를 보니까 퀴즈, 달, 타이머는 시작 전 카운트다운이 없군요....!!!!! 타이머 게임 카운트다운 빼겠습니다..ㅎ

2024-04-25 16:08 UTC, leehe228 requested changes
구현하신거 확인했습니다!! 리뷰 하나 확인 부탁드려요..!!

2024-04-25 16:27 UTC, Guryss commented
리뷰 반영하여 코드 수정했습니다!

2024-04-26 14:11 UTC, leehe228 commented on playkuround-iOS/Views/Games/QuizGame/QuizGameViewModel.swift
> +        randomNumber = Int.random(in: 0..<data.count)
P1;
0번 인덱스는 사용하지 않는 인덱스이므로
```swift
randomNumber = Int.random(in: 0..<data.count) + 1
```
로 수정해야 할 것 같아요 실제로 돌리다 보면 0번이 인덱스로 지정되어 아래처럼 아무것도 안보이는 화면이 나오네요!
<img src="https://github.com/playkuround/playkuround-iOS/assets/37548919/34d703af-6f9d-4ed3-b6c9-29703f78495d" width="280px"/>

2024-04-26 14:11 UTC, leehe228 requested changes
리뷰 확인해주세요!!!

2024-04-26 14:13 UTC, leehe228 commented on playkuround-iOS/Views/Games/QuizGame/QuizGameViewModel.swift
> +        randomNumber = Int.random(in: 0..<data.count)
QuizData.json도

```json
[
{
    "question" : "",
    "options" : ["",
                 "",
                 "",
                 ""],
    "answer" : 0
},
{
 "실제 데이터"
},
```
이렇게 되는게 맞을까요? 업데이트된 QuizData.json 파일도 노션에 업데이트 해주시면 좋을 것 같아요!

2024-04-26 14:22 UTC, Guryss commented on playkuround-iOS/Views/Games/QuizGame/QuizGameViewModel.swift
> +        randomNumber = Int.random(in: 0..<data.count)
아이고 그렇군요. 그부분을 생각 못했습니다. 수정할게요~!

QuizData.json 파일 수정 맞습니다~

2024-04-26 14:34 UTC, leehe228 approved these changes
잘 돌아가네요! 수고하셨어요!

2024-04-26 14:39 UTC, merged