Design#74
playkuround/playkuround-iOS pull request #81
Opened 2024-05-02 12:53 UTC by Guryss

### 🐣Issue

<br/>

### 🐣Motivation

<br/>

### 🐣Key Changes

<br/>

```swift
abc
```
<br/>

### 🐣Simulation
// UI를 구현했다면 시연영상은 필수 !

<br/>

### 🐣To Reviewer

<br/>

### 🐣Reference

<br/>

2024-05-13 03:28 UTC, leehe228 commented
리뷰가 늦어 죄송합니다

<img width="480px" alt="스크린샷 2024-05-13 10 29 12" src="https://github.com/playkuround/playkuround-iOS/assets/37548919/7cfeb108-a75d-4e0f-8bef-3a4f0edbc5bb">

혹시 키보드와 흰색 박스 사이에 간격은 없앨 수 없을까요?

2024-05-13 03:30 UTC, leehe228 commented
P2;

<img width="420px" alt="스크린샷 2024-05-13 12 26 20" src="https://github.com/playkuround/playkuround-iOS/assets/37548919/02f81cb6-c465-4024-af4b-0d83416d7a91">

현재 InputText에서 입력 텍스트 길어지면 다음줄로 넘어가는데 1줄로 만들어야 할 것 같습니다.
(위는 Android 캡쳐입니다)

2024-05-13 03:30 UTC, leehe228 commented
P1;
가운데 접시?들고있는 덕쿠가 없는데 일부러 빼신걸까요??

2024-05-13 03:36 UTC, leehe228 requested changes
리뷰가 늦어져서 죄송합니다 😭
리뷰 내용 확인 부탁드려요!

2024-05-13 08:17 UTC, Guryss commented
> P1; 가운데 접시?들고있는 덕쿠가 없는데 일부러 빼신걸까요??

아 저 이 부분이 궁금했는데 저 덕쿠가 어떻게 작동되는건지 몰라서 안넣었거든요!
그때 플레이 영상 기획 측에 부탁드렸는데 답장이 없길래 ... 😭😭😭
영상 있다면 보내주심 감사할 것 같아유!!

2024-05-15 18:23 UTC, Guryss commented
@leehe228 
<img width="1215" alt="image" src="https://github.com/playkuround/playkuround-iOS/assets/102604192/1519deaa-e412-43da-8bb9-54b0deda47b3">
덕쿠 이미지를 넣는 과정에서 키보드가 올라오다보니 이미지가 잘리는 현상이 발생합니다!
흠... 어떻게 하는 게 좋을까요?? 백그라운드 이미지를 더 올려서 최대한 덕쿠 얼굴이 보일 수 있도록 해야할까요?

2024-05-15 18:25 UTC, leehe228 commented
> @leehe228 <img alt="image" width="1215" src="https://private-user-images.githubusercontent.com/102604192/330917738-1519deaa-e412-43da-8bb9-54b0deda47b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3OTc3NTMsIm5iZiI6MTcxNTc5NzQ1MywicGF0aCI6Ii8xMDI2MDQxOTIvMzMwOTE3NzM4LTE1MTlkZWFhLWU0MTItNDNkYS04YmI5LTU0YjBkZWRhNDdiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNVQxODI0MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZThkYTE0ODk1Y2I0OTU5YjlhOGRkYWZjYzEwN2MzNTAwOGY3Mjc1ZWRkMTkyNmRmYjIzZTAzMTE4NmUyNGFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.a2GpZQTrWjTj5DyODQF48Pjgzh5lEdnlxcjbz4NI2qQ"> 덕쿠 이미지를 넣는 과정에서 키보드가 올라오다보니 이미지가 잘리는 현상이 발생합니다! 흠... 어떻게 하는 게 좋을까요?? 백그라운드 이미지를 더 올려서 최대한 덕쿠 얼굴이 보일 수 있도록 해야할까요?

음 제 개인적인 생각으로는 어차피 계속 키보드가 올라와있을 것이기 때문에 덕쿠를 좀 더 올려서 보이게 하는게 좋을 것 같습니다!

2024-05-16 18:08 UTC, Guryss commented
<img width="900" alt="image" src="https://github.com/playkuround/playkuround-iOS/assets/102604192/3ecafafb-bf09-4a7a-acc2-a632bda57725">

| iPhone SE 3rd | iPhone XS | iPhone 15 Pro |
| - | - | - |

해결 완료했습니다~
@leehe228

2024-05-16 19:31 UTC, leehe228 approved these changes
확인했습니다 고생많으셨습니다!

2024-05-17 00:58 UTC, merged